      let resultText = `✅ **Persona "${personaData.name}" created successfully!**\n\n`;
      resultText += `🆔 **ID:** ${personaData.id}\n`;
      resultText += `📝 **Description:** ${personaData.description || 'None'}\n`;
      resultText += `🎛️ **Settings:**\n`;
      resultText += `  • Temperature: ${personaData.temperature || validParams.temperature || 0.7}\n`;
      resultText += `  • Max Tokens: ${personaData.maxTokens || validParams.maxTokens || 2048}\n`;
      resultText += `  • Embedding Provider: ${personaData.embeddingProvider || validParams.embeddingProvider || 'local'}\n`;
      resultText += `  • Max Memory Size: ${personaData.maxMemorySize || 1000}\n`;
      resultText += `  • Memory Decay: ${Math.round((personaData.memoryDecayTime || 7 * 24 * 60 * 60 * 1000) / (24 * 60 * 60 * 1000))} days`;
